### ISSUE TITLE
Only works after page reload

### ISSUE THREAD

**Issue by piggaaon** [HatScripts/YouTubeAutoLiker#2]
Sometime in early 2018, Youtube change something in their code. Using Tampermonkey, the YouTubeAutoLiker script will load after refreshing the page. See this issue on both Firefox and Chrome. Also see feedback on Greasy Fork as other people are see same issue.

**Comment by HatScripts** [comment]
Hi, thanks for the bug report. I just pushed a commit (and updated the userscript to v1.2.0) which should have fixed this problem. Please let me know if you run into any further issues.

**Comment by piggaaon** [comment]
Still cannot get YouTubeAutoLiker to load with Tampermonkey when trying to watch video. See my workaround below, it is not elegant as script loads when just going to youtube.com. 
Below is setup, list other TM scripts installed, they should not be affecting this script loading but listing anyway.

My Setup:
NOTE: Use browsers from https://portableapps.com
Browser(s): Firefox [65.0 (64-bit)], Google Chrome [72.0.3626.96 (Official Build) (32-bit)]
Tampermonkey (4.8) (https://tampermonkey.net)
Other TM scripts Running:
Disable Youtube autoplay (https://greasyfork.org/en/scripts/34651-disable-youtube-autoplay)
See more without logging into Facebook (https://greasyfork.org/en/scripts/21627-see-more-without-logging-into-facebook)
Youtube: Space to Pause (https://greasyfork.org/en/scripts/13386-youtube-space-to-pause)

Workaround:
Remove "watch" from url (WARNING: this change will load this script on any page at youtube.com).
From:
// @match          http://*.youtube.com/watch*
// @match          https://*.youtube.com/watch*
To:
// @match          http://*.youtube.com/*
// @match          https://*.youtube.com/*

**Comment by HatScripts** [comment]
Thanks @piggaaon, for now I'll push your workaround until I find a solution that doesn't load the script on every YouTube page. Though that's probably not that big of a deal, because the userscript is only run at `document-idle` meaning after all other page resources have been loaded, so it shouldn't affect page load times at least.

**Comment by HatScripts** [comment]
Closing this issue as your fix is still working. I will update the script soon to use onpopstate to watch the URL for changes.

Though from my initial tests it doesn't appear that the `popstate` event is triggered by YouTube when navigating from, for example, the homepage to a video page, despite the URL changing. According to MDN:

>Note: Calling `history.pushState()` or `history.replaceState()` won't trigger a `popstate` event. The `popstate` event is only triggered by performing a browser action, such as clicking on the back button (or calling `history.back()` in JavaScript), when navigating between two history entries for the same document.

Ultimately I think we could just ignore the URL completely and rely on [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver)s that watch the DOM for the relevant changes.
